import Foundation

/// The role of a chat message sender.
enum MessageRole: String, Codable, Sendable {
    case user
    case assistant
    case system
}

/// A source reference cited in an assistant's response.
struct ChatSourceReference: Codable, Identifiable, Hashable, Sendable {
    var id: String?
    var title: String?
    var url: String?
    var snippet: String?
    var type: String?
    var metadata: [String: String]?

    /// Resolves the best available URL from all possible fields,
    /// matching the Flutter app's `_getSourceUrl` logic.
    var resolvedURL: String? {
        // Direct url field
        if let url, !url.isEmpty, url.hasPrefix("http") { return url }
        // ID might be a URL
        if let id, id.hasPrefix("http") { return id }
        // Title might be a URL
        if let title, title.hasPrefix("http") { return title }
        // Check metadata fields
        if let meta = metadata {
            if let s = meta["source"], s.hasPrefix("http") { return s }
            if let u = meta["url"], u.hasPrefix("http") { return u }
            if let l = meta["link"], l.hasPrefix("http") { return l }
        }
        return nil
    }
}

/// A status update during message streaming (e.g., tool calls, web searches).
struct ChatStatusUpdate: Codable, Sendable {
    var action: String?
    var description: String?
    var done: Bool?
    var hidden: Bool?
    var urls: [String]
    var occurredAt: Date?

    init(
        action: String? = nil,
        description: String? = nil,
        done: Bool? = nil,
        hidden: Bool? = nil,
        urls: [String] = [],
        occurredAt: Date? = nil
    ) {
        self.action = action
        self.description = description
        self.done = done
        self.hidden = hidden
        self.urls = urls
        self.occurredAt = occurredAt
    }
}

/// Represents a single message in a chat conversation.
/// A file attached to or generated by a message (images from tools, uploads, etc.)
struct ChatMessageFile: Codable, Hashable, Sendable {
    var type: String?       // "image", "file"
    var url: String?        // file ID or URL path
    var name: String?
    var contentType: String?
}

struct ChatMessage: Codable, Identifiable, Hashable, Sendable {
    let id: String
    var role: MessageRole
    var content: String
    var timestamp: Date
    var model: String?
    var isStreaming: Bool
    var attachmentIds: [String]
    var files: [ChatMessageFile]
    var sources: [ChatSourceReference]
    var statusHistory: [ChatStatusUpdate]
    var followUps: [String]
    var metadata: [String: String]?
    var error: ChatMessageError?
    var versions: [ChatMessageVersion]

    init(
        id: String = UUID().uuidString,
        role: MessageRole,
        content: String,
        timestamp: Date = .now,
        model: String? = nil,
        isStreaming: Bool = false,
        attachmentIds: [String] = [],
        files: [ChatMessageFile] = [],
        sources: [ChatSourceReference] = [],
        statusHistory: [ChatStatusUpdate] = [],
        followUps: [String] = [],
        metadata: [String: String]? = nil,
        error: ChatMessageError? = nil,
        versions: [ChatMessageVersion] = []
    ) {
        self.id = id
        self.role = role
        self.content = content
        self.timestamp = timestamp
        self.model = model
        self.isStreaming = isStreaming
        self.attachmentIds = attachmentIds
        self.files = files
        self.sources = sources
        self.statusHistory = statusHistory
        self.followUps = followUps
        self.metadata = metadata
        self.error = error
        self.versions = versions
    }

    /// O(1) equality check — uses `content.utf8.count` instead of full string
    /// comparison. During streaming, content only grows so byte count is always
    /// unique. For completed messages, content is stable. This avoids O(n)
    /// character-by-character comparison on potentially huge AI responses during
    /// every SwiftUI diff cycle (~7x/sec during streaming).
    static func == (lhs: ChatMessage, rhs: ChatMessage) -> Bool {
        lhs.id == rhs.id
            && lhs.content.utf8.count == rhs.content.utf8.count
            && lhs.isStreaming == rhs.isStreaming
            && lhs.statusHistory.count == rhs.statusHistory.count
            && lhs.sources.count == rhs.sources.count
            && lhs.followUps.count == rhs.followUps.count
            && lhs.files.count == rhs.files.count
            && lhs.error?.content == rhs.error?.content
            && lhs.versions.count == rhs.versions.count
    }

    func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(content.utf8.count)
        hasher.combine(isStreaming)
        hasher.combine(followUps.count)
        hasher.combine(files.count)
        hasher.combine(versions.count)
    }
}

/// A previous version of an assistant response, stored when the user
/// retries / regenerates a response.
///
/// Each version corresponds to a **sibling message** in the OpenWebUI
/// history tree. The `id` field tracks the sibling's message ID so
/// we can round-trip versions through the server without duplication.
struct ChatMessageVersion: Codable, Hashable, Sendable {
    /// Sibling message ID in the OpenWebUI history tree.
    /// Generated locally for app-created versions; preserved from server
    /// for server-created siblings.
    var id: String
    var content: String
    var timestamp: Date
    var model: String?
    var error: ChatMessageError?
    var files: [ChatMessageFile]
    var sources: [ChatSourceReference]
    var followUps: [String]

    init(
        id: String = UUID().uuidString,
        content: String,
        timestamp: Date = .now,
        model: String? = nil,
        error: ChatMessageError? = nil,
        files: [ChatMessageFile] = [],
        sources: [ChatSourceReference] = [],
        followUps: [String] = []
    ) {
        self.id = id
        self.content = content
        self.timestamp = timestamp
        self.model = model
        self.error = error
        self.files = files
        self.sources = sources
        self.followUps = followUps
    }

    // Custom decoder for backwards compatibility — if `id` is missing
    // from JSON (e.g., cached data from before this field existed),
    // fall back to a new UUID.
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.id = (try? container.decode(String.self, forKey: .id)) ?? UUID().uuidString
        self.content = try container.decode(String.self, forKey: .content)
        self.timestamp = try container.decode(Date.self, forKey: .timestamp)
        self.model = try container.decodeIfPresent(String.self, forKey: .model)
        self.error = try container.decodeIfPresent(ChatMessageError.self, forKey: .error)
        self.files = (try? container.decode([ChatMessageFile].self, forKey: .files)) ?? []
        self.sources = (try? container.decode([ChatSourceReference].self, forKey: .sources)) ?? []
        self.followUps = (try? container.decode([String].self, forKey: .followUps)) ?? []
    }
}

/// Error information for a chat message, matching OpenWebUI's error format.
struct ChatMessageError: Codable, Hashable, Sendable {
    var content: String?
}
