import Foundation

/// The role of a chat message sender.
enum MessageRole: String, Codable, Sendable {
    case user
    case assistant
    case system
}

/// A source reference cited in an assistant's response.
struct ChatSourceReference: Codable, Identifiable, Hashable, Sendable {
    var id: String?
    var title: String?
    var url: String?
    var snippet: String?
    var type: String?
    var metadata: [String: String]?

    /// A short, human-readable label for inline citation badges.
    /// Mirrors the OpenWebUI web interface which shows shortened page
    /// titles instead of numeric IDs.
    ///
    /// Priority: non-URL title → domain name from URL → nil (caller
    /// should fall back to the citation number).
    var displayLabel: String? {
        // 1. Use the title if it's a real title (not a raw URL)
        if let title, !title.isEmpty, !title.hasPrefix("http") {
            return Self.truncateTitle(title, maxLength: 24)
        }
        // 2. Fall back to a cleaned-up domain name
        if let url = resolvedURL, let domain = Self.domainFromURL(url) {
            return domain
        }
        return nil
    }

    /// Truncates a title to `maxLength`, adding "..." if needed.
    private static func truncateTitle(_ title: String, maxLength: Int) -> String {
        let trimmed = title.trimmingCharacters(in: .whitespacesAndNewlines)
        guard trimmed.count > maxLength else { return trimmed }
        return String(trimmed.prefix(maxLength - 3)) + "..."
    }

    /// Extracts a display-friendly domain from a URL string.
    private static func domainFromURL(_ url: String) -> String? {
        guard let parsed = URL(string: url), let host = parsed.host else { return nil }
        var domain = host
        if domain.hasPrefix("www.") { domain = String(domain.dropFirst(4)) }
        return domain.isEmpty ? nil : domain
    }

    /// Resolves the best available URL from all possible fields,
    /// matching the Flutter app's `_getSourceUrl` logic.
    var resolvedURL: String? {
        // Direct url field
        if let url, !url.isEmpty, url.hasPrefix("http") { return url }
        // ID might be a URL
        if let id, id.hasPrefix("http") { return id }
        // Title might be a URL
        if let title, title.hasPrefix("http") { return title }
        // Check metadata fields
        if let meta = metadata {
            if let s = meta["source"], s.hasPrefix("http") { return s }
            if let u = meta["url"], u.hasPrefix("http") { return u }
            if let l = meta["link"], l.hasPrefix("http") { return l }
        }
        return nil
    }
}

/// A status update during message streaming (e.g., tool calls, web searches).
struct ChatStatusUpdate: Codable, Sendable {
    var action: String?
    var description: String?
    var done: Bool?
    var hidden: Bool?
    var urls: [String]
    var occurredAt: Date?
    /// The number of results (e.g. "Retrieved 17 sources").
    var count: Int?
    /// A single search/retrieval query string.
    var query: String?
    /// Multiple search queries generated by the server.
    var queries: [String]

    init(
        action: String? = nil,
        description: String? = nil,
        done: Bool? = nil,
        hidden: Bool? = nil,
        urls: [String] = [],
        occurredAt: Date? = nil,
        count: Int? = nil,
        query: String? = nil,
        queries: [String] = []
    ) {
        self.action = action
        self.description = description
        self.done = done
        self.hidden = hidden
        self.urls = urls
        self.occurredAt = occurredAt
        self.count = count
        self.query = query
        self.queries = queries
    }
}

/// Represents a single message in a chat conversation.
/// A file attached to or generated by a message (images from tools, uploads, etc.)
struct ChatMessageFile: Codable, Hashable, Sendable {
    var type: String?       // "image", "file"
    var url: String?        // file ID or URL path
    var name: String?
    var contentType: String?
}

struct ChatMessage: Identifiable, Hashable, Sendable {
    let id: String
    var role: MessageRole
    var content: String
    var timestamp: Date
    var model: String?
    var isStreaming: Bool
    var attachmentIds: [String]
    var files: [ChatMessageFile]
    var sources: [ChatSourceReference]
    var statusHistory: [ChatStatusUpdate]
    var followUps: [String]
    var metadata: [String: String]?
    var error: ChatMessageError?
    var versions: [ChatMessageVersion]
    /// Token usage data returned by the server after generation completes.
    /// Stored as a raw dictionary so any provider-specific fields are preserved
    /// regardless of model (OpenAI, Anthropic, Ollama, etc. all differ).
    var usage: [String: Any]?
    /// Rich UI HTML embeds stored at the message level by the server.
    /// OpenWebUI stores embeds here when the tool call's `<details>` block
    /// has an empty `embeds=""` attribute — the HTML is instead placed on the
    /// message object itself. The iOS app renders these via `RichUIEmbedView`
    /// (the same WKWebView path used for tool-level embeds).
    var embeds: [String]

    init(
        id: String = UUID().uuidString,
        role: MessageRole,
        content: String,
        timestamp: Date = .now,
        model: String? = nil,
        isStreaming: Bool = false,
        attachmentIds: [String] = [],
        files: [ChatMessageFile] = [],
        sources: [ChatSourceReference] = [],
        statusHistory: [ChatStatusUpdate] = [],
        followUps: [String] = [],
        metadata: [String: String]? = nil,
        error: ChatMessageError? = nil,
        versions: [ChatMessageVersion] = [],
        usage: [String: Any]? = nil,
        embeds: [String] = []
    ) {
        self.id = id
        self.role = role
        self.content = content
        self.timestamp = timestamp
        self.model = model
        self.isStreaming = isStreaming
        self.attachmentIds = attachmentIds
        self.files = files
        self.sources = sources
        self.statusHistory = statusHistory
        self.followUps = followUps
        self.metadata = metadata
        self.error = error
        self.versions = versions
        self.usage = usage
        self.embeds = embeds
    }

    /// O(1) equality check — uses `content.utf8.count` instead of full string
    /// comparison. During streaming, content only grows so byte count is always
    /// unique. For completed messages, content is stable. This avoids O(n)
    /// character-by-character comparison on potentially huge AI responses during
    /// every SwiftUI diff cycle (~7x/sec during streaming).
    static func == (lhs: ChatMessage, rhs: ChatMessage) -> Bool {
        lhs.id == rhs.id
            && lhs.content.utf8.count == rhs.content.utf8.count
            && lhs.isStreaming == rhs.isStreaming
            && lhs.statusHistory.count == rhs.statusHistory.count
            && lhs.sources.count == rhs.sources.count
            && lhs.followUps.count == rhs.followUps.count
            && lhs.files.count == rhs.files.count
            && lhs.error?.content == rhs.error?.content
            && lhs.versions.count == rhs.versions.count
            && (lhs.usage == nil) == (rhs.usage == nil)
    }

    func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(content.utf8.count)
        hasher.combine(isStreaming)
        hasher.combine(followUps.count)
        hasher.combine(files.count)
        hasher.combine(versions.count)
    }
}

// MARK: - ChatMessage Codable

extension ChatMessage: Codable {
    enum CodingKeys: String, CodingKey {
        case id, role, content, timestamp, model, isStreaming
        case attachmentIds, files, sources, statusHistory, followUps
        case metadata, error, versions, usage
    }

    init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        id            = try c.decode(String.self, forKey: .id)
        role          = try c.decode(MessageRole.self, forKey: .role)
        content       = try c.decode(String.self, forKey: .content)
        timestamp     = try c.decode(Date.self, forKey: .timestamp)
        model         = try c.decodeIfPresent(String.self, forKey: .model)
        isStreaming   = (try? c.decode(Bool.self, forKey: .isStreaming)) ?? false
        attachmentIds = (try? c.decode([String].self, forKey: .attachmentIds)) ?? []
        files         = (try? c.decode([ChatMessageFile].self, forKey: .files)) ?? []
        sources       = (try? c.decode([ChatSourceReference].self, forKey: .sources)) ?? []
        statusHistory = (try? c.decode([ChatStatusUpdate].self, forKey: .statusHistory)) ?? []
        followUps     = (try? c.decode([String].self, forKey: .followUps)) ?? []
        metadata      = try? c.decodeIfPresent([String: String].self, forKey: .metadata)
        error         = try? c.decodeIfPresent(ChatMessageError.self, forKey: .error)
        versions      = (try? c.decode([ChatMessageVersion].self, forKey: .versions)) ?? []
        // usage is [String: Any] — decode via JSONSerialization-backed AnyCodable bridge
        if let usageData = try? c.decodeIfPresent(AnyCodableMap.self, forKey: .usage) {
            usage = usageData.value
        } else {
            usage = nil
        }
        // embeds are not persisted — they come from the server JSON on each load.
        embeds = []
    }

    func encode(to encoder: Encoder) throws {
        var c = encoder.container(keyedBy: CodingKeys.self)
        try c.encode(id, forKey: .id)
        try c.encode(role, forKey: .role)
        try c.encode(content, forKey: .content)
        try c.encode(timestamp, forKey: .timestamp)
        try c.encodeIfPresent(model, forKey: .model)
        try c.encode(isStreaming, forKey: .isStreaming)
        try c.encode(attachmentIds, forKey: .attachmentIds)
        try c.encode(files, forKey: .files)
        try c.encode(sources, forKey: .sources)
        try c.encode(statusHistory, forKey: .statusHistory)
        try c.encode(followUps, forKey: .followUps)
        try c.encodeIfPresent(metadata, forKey: .metadata)
        try c.encodeIfPresent(error, forKey: .error)
        try c.encode(versions, forKey: .versions)
        if let usage {
            try c.encode(AnyCodableMap(usage), forKey: .usage)
        }
    }
}

// MARK: - AnyCodableMap (bridges [String: Any] ↔ Codable)

/// A lightweight Codable wrapper around `[String: Any]` that handles
/// nested dictionaries, arrays, numbers, booleans and strings.
/// Used exclusively for persisting/restoring `ChatMessage.usage`.
struct AnyCodableMap: Codable {
    let value: [String: Any]

    init(_ value: [String: Any]) { self.value = value }

    init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        value = (try? container.decode([String: AnyDecodable].self))?.mapValues(\.value) ?? [:]
    }

    func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        let encodable = value.mapValues { AnyEncodable($0) }
        try container.encode(encodable)
    }
}

// Decoding helper
private struct AnyDecodable: Decodable {
    let value: Any

    init(from decoder: Decoder) throws {
        let c = try decoder.singleValueContainer()
        if let v = try? c.decode(Bool.self)   { value = v; return }
        if let v = try? c.decode(Int.self)    { value = v; return }
        if let v = try? c.decode(Double.self) { value = v; return }
        if let v = try? c.decode(String.self) { value = v; return }
        if let v = try? c.decode([String: AnyDecodable].self) {
            value = v.mapValues(\.value); return
        }
        if let v = try? c.decode([AnyDecodable].self) {
            value = v.map(\.value); return
        }
        value = NSNull()
    }
}

// Encoding helper
private struct AnyEncodable: Encodable {
    let wrapped: Any
    init(_ value: Any) { wrapped = value }

    func encode(to encoder: Encoder) throws {
        var c = encoder.singleValueContainer()
        switch wrapped {
        case let v as Bool:           try c.encode(v)
        case let v as Int:            try c.encode(v)
        case let v as Double:         try c.encode(v)
        case let v as Float:          try c.encode(Double(v))
        case let v as String:         try c.encode(v)
        case let v as [String: Any]:  try c.encode(v.mapValues { AnyEncodable($0) })
        case let v as [Any]:          try c.encode(v.map { AnyEncodable($0) })
        default:                      try c.encodeNil()
        }
    }
}

/// A previous version of an assistant response, stored when the user
/// retries / regenerates a response.
///
/// Each version corresponds to a **sibling message** in the OpenWebUI
/// history tree. The `id` field tracks the sibling's message ID so
/// we can round-trip versions through the server without duplication.
///
/// For **user message versions** (edit history), `pairedAssistantId`
/// stores the ID of the assistant message that responded to this version
/// of the user message. This allows the UI to switch the displayed AI
/// response when the user navigates between edit versions.
struct ChatMessageVersion: Codable, Equatable, Hashable, Sendable {
    enum CodingKeys: String, CodingKey {
        case id, content, timestamp, model, error, files, sources, followUps, usage
        case pairedAssistantId, pairedAssistantContent, pairedAssistantModel
        case pairedAssistantFiles, pairedAssistantSources, pairedAssistantVersions
        case downstreamMessages
    }

    /// Sibling message ID in the OpenWebUI history tree.
    /// Generated locally for app-created versions; preserved from server
    /// for server-created siblings.
    var id: String
    var content: String
    var timestamp: Date
    var model: String?
    var error: ChatMessageError?
    var files: [ChatMessageFile]
    var sources: [ChatSourceReference]
    var followUps: [String]
    /// Token usage for this specific version, captured when the response completes.
    var usage: [String: Any]?
    /// For user message versions only: the ID of the assistant message
    /// that is the active (current) response to this user version.
    var pairedAssistantId: String?

    /// For user message versions only: stores the AI response content that was
    /// generated in response to this (older) user message version.
    var pairedAssistantContent: String?
    var pairedAssistantModel: String?
    var pairedAssistantFiles: [ChatMessageFile]
    var pairedAssistantSources: [ChatSourceReference]

    /// Regeneration versions for the OLD branch's assistant message.
    /// When the user regenerated the AI response multiple times on the old
    /// branch before editing the user message, those are stored here so
    /// they can be restored if the user switches back to this branch.
    var pairedAssistantVersions: [ChatMessageVersion]

    /// Messages that came AFTER the user+assistant pair on this old branch
    /// (i.e., the continuation of the conversation). Stored here so that
    /// switching to this branch restores the full context.
    var downstreamMessages: [ChatMessage]

    init(
        id: String = UUID().uuidString,
        content: String,
        timestamp: Date = .now,
        model: String? = nil,
        error: ChatMessageError? = nil,
        files: [ChatMessageFile] = [],
        sources: [ChatSourceReference] = [],
        followUps: [String] = [],
        usage: [String: Any]? = nil,
        pairedAssistantId: String? = nil,
        pairedAssistantContent: String? = nil,
        pairedAssistantModel: String? = nil,
        pairedAssistantFiles: [ChatMessageFile] = [],
        pairedAssistantSources: [ChatSourceReference] = [],
        pairedAssistantVersions: [ChatMessageVersion] = [],
        downstreamMessages: [ChatMessage] = []
    ) {
        self.id = id
        self.content = content
        self.timestamp = timestamp
        self.model = model
        self.error = error
        self.files = files
        self.sources = sources
        self.followUps = followUps
        self.usage = usage
        self.pairedAssistantId = pairedAssistantId
        self.pairedAssistantContent = pairedAssistantContent
        self.pairedAssistantModel = pairedAssistantModel
        self.pairedAssistantFiles = pairedAssistantFiles
        self.pairedAssistantSources = pairedAssistantSources
        self.pairedAssistantVersions = pairedAssistantVersions
        self.downstreamMessages = downstreamMessages
    }

    // Custom decoder for backwards compatibility — if fields are missing
    // from JSON (e.g., cached data from before this field existed),
    // fall back to defaults.
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.id = (try? container.decode(String.self, forKey: .id)) ?? UUID().uuidString
        self.content = try container.decode(String.self, forKey: .content)
        self.timestamp = try container.decode(Date.self, forKey: .timestamp)
        self.model = try container.decodeIfPresent(String.self, forKey: .model)
        self.error = try container.decodeIfPresent(ChatMessageError.self, forKey: .error)
        self.files = (try? container.decode([ChatMessageFile].self, forKey: .files)) ?? []
        self.sources = (try? container.decode([ChatSourceReference].self, forKey: .sources)) ?? []
        self.followUps = (try? container.decode([String].self, forKey: .followUps)) ?? []
        if let usageData = try? container.decodeIfPresent(AnyCodableMap.self, forKey: .usage) {
            self.usage = usageData.value
        } else {
            self.usage = nil
        }
        self.pairedAssistantId = try? container.decodeIfPresent(String.self, forKey: .pairedAssistantId)
        self.pairedAssistantContent = try? container.decodeIfPresent(String.self, forKey: .pairedAssistantContent)
        self.pairedAssistantModel = try? container.decodeIfPresent(String.self, forKey: .pairedAssistantModel)
        self.pairedAssistantFiles = (try? container.decode([ChatMessageFile].self, forKey: .pairedAssistantFiles)) ?? []
        self.pairedAssistantSources = (try? container.decode([ChatSourceReference].self, forKey: .pairedAssistantSources)) ?? []
        self.pairedAssistantVersions = (try? container.decode([ChatMessageVersion].self, forKey: .pairedAssistantVersions)) ?? []
        self.downstreamMessages = (try? container.decode([ChatMessage].self, forKey: .downstreamMessages)) ?? []
    }

    func encode(to encoder: Encoder) throws {
        var c = encoder.container(keyedBy: CodingKeys.self)
        try c.encode(id, forKey: .id)
        try c.encode(content, forKey: .content)
        try c.encode(timestamp, forKey: .timestamp)
        try c.encodeIfPresent(model, forKey: .model)
        try c.encodeIfPresent(error, forKey: .error)
        try c.encode(files, forKey: .files)
        try c.encode(sources, forKey: .sources)
        try c.encode(followUps, forKey: .followUps)
        if let usage {
            try c.encode(AnyCodableMap(usage), forKey: .usage)
        }
        try c.encodeIfPresent(pairedAssistantId, forKey: .pairedAssistantId)
        try c.encodeIfPresent(pairedAssistantContent, forKey: .pairedAssistantContent)
        try c.encodeIfPresent(pairedAssistantModel, forKey: .pairedAssistantModel)
        try c.encode(pairedAssistantFiles, forKey: .pairedAssistantFiles)
        try c.encode(pairedAssistantSources, forKey: .pairedAssistantSources)
        try c.encode(pairedAssistantVersions, forKey: .pairedAssistantVersions)
        try c.encode(downstreamMessages, forKey: .downstreamMessages)
    }

    // Manual Equatable — compares all fields except `usage` ([String: Any] isn't Equatable).
    // usage is compared by presence only (nil vs non-nil) to avoid false positives.
    static func == (lhs: ChatMessageVersion, rhs: ChatMessageVersion) -> Bool {
        lhs.id == rhs.id
            && lhs.content == rhs.content
            && lhs.timestamp == rhs.timestamp
            && lhs.model == rhs.model
            && lhs.error == rhs.error
            && lhs.files == rhs.files
            && lhs.sources == rhs.sources
            && lhs.followUps == rhs.followUps
            && (lhs.usage == nil) == (rhs.usage == nil)
            && lhs.pairedAssistantId == rhs.pairedAssistantId
            && lhs.pairedAssistantContent == rhs.pairedAssistantContent
            && lhs.pairedAssistantModel == rhs.pairedAssistantModel
            && lhs.pairedAssistantFiles == rhs.pairedAssistantFiles
            && lhs.pairedAssistantSources == rhs.pairedAssistantSources
            && lhs.pairedAssistantVersions == rhs.pairedAssistantVersions
            && lhs.downstreamMessages == rhs.downstreamMessages
    }

    // Manual Hashable — hashes all Hashable fields; usage is hashed by presence only.
    func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(content)
        hasher.combine(timestamp)
        hasher.combine(model)
        hasher.combine(error)
        hasher.combine(files)
        hasher.combine(sources)
        hasher.combine(followUps)
        hasher.combine(usage != nil)
        hasher.combine(pairedAssistantId)
        hasher.combine(pairedAssistantContent)
        hasher.combine(pairedAssistantModel)
    }
}

/// Error information for a chat message, matching OpenWebUI's error format.
struct ChatMessageError: Codable, Hashable, Sendable {
    var content: String?
}
